
apiVersion: networking.k8s.io/v1
kind: ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              services: 
                name: frontend
                port:
                  number:8080
                  




